#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/zshrc" "$HOME"/.zshrc
ln -sf "$PWD/tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/lazygit.yml" "$XDG_CONFIG_HOME"/lazygit/config.yml
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix


# Install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages

# Install TPM
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Set zsh as default shell
sudo chsh "$(id -un)" --shell "/usr/bin/zsh"

